server:
  port: 8760

spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serverUrl:
      defaultZone: http://localhost:8760/eureka/