server:
  port: 8085

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-services
          uri: http://localhost:9092
          predicates:
            - Path=/api/auth/**

eureka:
  client:
    register-with-eureka: false