server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080,http://localhost:8888,http://localhost:8761,http://localhost:8090,http://localhost:9090"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: http://localhost:8090
          predicates:
            - Path=/api/user/**
        - id: authentication
          uri: http://localhost:9090
          predicates:
            - Path=/api/auth/**

eureka:
  client:
    register-with-eureka: false