server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: http://localhost:8090
          predicates:
            - Path=/api/user/**
        - id: authentication
          uri: http://localhost:9090
          predicates:
            - Path=/api/auth/**
        - id: auth-services
          uri: http://localhost:9094
          predicates:
            - Path=/auth/**

eureka:
  client:
    register-with-eureka: false